name: Eventuate
rating: 5
imageUrl: https://github.com/msa-ez/template-spring-boot-3/assets/123912988/90070797-828e-4746-b660-d9e190d2eca8
templateName: eventuate
description: By addressing the unique distributed data management challenges of Microservices Architecture, enables developers to focus on business logic.
group: Eventuate
